### ISSUE TITLE
Configurar painéis Grafana para bloquear edição por qualquer usuário

### ISSUE THREAD

**Issue by OmarGhoche** [pontus-vision/pontus-grafana-react-panel#10]
**Resumo:**
Configurar painéis Grafana para bloquear edição por qualquer usuário

**Como um:**
Pontus Vision Engineer

**Eu quero:**
Configurar painéis Grafana para bloquear edição por qualquer usuário, retirando a engrenagem para usuários que não sejam administradores

**Para que:**
Não ser possível qualquer um deletar ou editar os painéis

![image](https://user-images.githubusercontent.com/17257630/186472294-d0c4ecbb-ee90-4b12-89bd-2e138481ef8a.png)

**Comment by AmandaMozena** [comment]
Solução: criar usuário no Grafana como ready only.
